name: elegant
channels:
- conda-forge
dependencies:
- python>=3.6
- numpy>=1.17
- matplotlib>=3.1.2
- scipy>=1.3.2
- jupyter>=1.0
- plotly>=5.0
- pip:
  # not available on conda, so use pip
  - jupytercontrib>=0.0.7
